stages:
  - freeze
  - build
  - release

freeze-tag:
  stage: freeze
  image: alpine
  artifacts:
      expire_in: 6 weeks
      reports:
        dotenv:
          - ci-job-date.env
          - image-name.env
          - image-url.env
  script:
    - echo "CI_JOB_DATE=$(date +%Y-%m-%d-%H%M%S)" >> ci-job-date.env
    - export IMAGE_NAME=frost
    - echo "IMAGE_NAME=${IMAGE_NAME}" >> image-name.env
    - echo "IMAGE_URL=${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" >> image-url.env

default:
  image: python:3.9

add-feature-branch-tags:
  stage: release
  except:
    - "main"
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag ${IMAGE_URL}:${CI_JOB_DATE} ${CI_COMMIT_BRANCH}

add-release-tags:
  stage: release
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      when: on_success
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag ${IMAGE_URL}:${CI_JOB_DATE} latest
