version: '3'

networks:
  db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16

services:
  frost:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - 8080:8080
      - 9876:9876
    volumes:
      - ./context/:/usr/local/tomcat/conf/Catalina/localhost/
    depends_on:
      - database
    networks:
      db_net:
        ipv4_address: 10.10.0.2

  database:
    image: postgis/postgis:11-2.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "{POSTGRES_DB: -postgres}"
      POSTGRES_USER: "{POSTGRES_USER: -postgres}"
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD: -postgres}"
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    networks:
      db_net:
         ipv4_address: 10.10.0.3

volumes:
  postgis_volume: